language: rust
rust:
- nightly

script: cd $CRATE && cargo build --verbose && cargo test --verbose

env:
- CRATE=factorio-mods-common
- CRATE=factorio-mods-api
- CRATE=factorio-mods-local
- CRATE=.

sudo: false
