language: rust
rust:
  - stable
script:
  - (cd factorio-mods-common && cargo build --verbose && cargo test --verbose)
  - (cd factorio-mods-api && cargo build --verbose && cargo test --verbose)
  - (cd factorio-mods-local && cargo build --verbose && cargo test --verbose)
  - (cd fac-rs && cargo build --verbose && cargo test --verbose)
sudo: false
