language: rust
rust:
- nightly

script: cd $CRATE && cargo build --verbose && cargo test --verbose && cargo install clippy && cargo clippy --verbose

env:
- CRATE=factorio-mods-common
- CRATE=factorio-mods-local
- CRATE=factorio-mods-web
- CRATE=package
- CRATE=.

sudo: false
