language: rust
rust:
- nightly

script: cd $CRATE && cargo build --verbose && cargo test --verbose && rustup component add clippy && cargo clippy --verbose && cargo clippy --tests --verbose

env:
- CRATE=factorio-mods-common
- CRATE=factorio-mods-local
- CRATE=factorio-mods-web
- CRATE=package
- CRATE=.

sudo: false
