language: rust
rust:
- nightly-2018-09-19

script: rustup component add clippy-preview && cd $CRATE && cargo build --verbose && cargo test --verbose && cargo clippy --verbose

env:
- CRATE=factorio-mods-common
- CRATE=factorio-mods-local
- CRATE=factorio-mods-web
- CRATE=package
- CRATE=.

sudo: false
