[package]
name = "factorio-mods-common"
version = "0.1.0"
authors = ["Arnavion <arnavion@gmail.com>"]

[dependencies]
derive-new = "0.3.x"
derive-struct = { version = "0.1.0", path = "../derive-struct" }
itertools = "0.5.x"
lazy_static = "0.2.x"
regex = "0.1.x"
semver = "0.5.x"
serde = "0.8.x"
serde_derive = "0.8.x"

[dev-dependencies]
serde_json = "0.8.x"
