[package]
name = "factorio-mods-common"
version = "0.1.0"
authors = ["Arnavion <arnavion@gmail.com>"]

[dependencies]
derive-new = "0.5.x"
derive-struct = { version = "0.1.0", path = "../derive-struct" }
itertools = "0.6.x"
lazy_static = "0.2.x"
regex = "0.2.x"
semver = "0.7.x"
serde = "1.0.x"
serde_derive = "1.0.x"

[dev-dependencies]
serde_json = "1.0.x"
