[package]
name = "factorio-mods-common"
version = "0.1.0"
authors = ["Arnavion <arnavion@gmail.com>"]
edition = "2018"

[dependencies]
derive-struct = { version = "0.1.0", path = "../derive-struct" }
itertools = "0.8.x"
lazy_static = "1"
package = { path = "../package" }
regex = "1.2"
semver = "0.9.x"
serde = "1.0.x"
serde_derive = "1.0.x"

[dev-dependencies]
serde_json = "1.0.x"
