[package]
name = "factorio-mods-common"
version = "0.1.0"
authors = ["Arnavion <arnavion@gmail.com>"]

[dependencies]
derive-new = { git = "https://github.com/nrc/derive-new", rev = "24e584908a783986a5fe079aca55c00526318142" }
itertools = "0.5.x"
derive-struct = { version = "0.1.0", path = "../derive-struct" }
semver = "0.5.x"
serde = "0.8.x"
serde_derive = "0.8.x"
