[package]
name = "factorio-mods-local"
version = "0.1.0"
authors = ["Arnavion <arnavion@gmail.com>"]

[dependencies]
appdirs = "0.2.x"
backtrace = "0.3.x"
derive-error-chain = "0.10.x"
derive-new = "0.4.x"
derive-struct = { version = "0.1.0", path = "../derive-struct" }
error-chain = "0.10.x"
factorio-mods-common = { version = "0.1.0", path = "../factorio-mods-common" }
glob = "0.2.x"
lazy_static = "0.2.x"
semver = "0.6.x"
serde = "0.9.x"
serde_derive = "0.9.x"
serde_json = "0.9.x"
zip = "0.2.x"
