[package]
name = "factorio-mods-local"
version = "0.1.0"
authors = ["Arnavion <arnavion@gmail.com>"]
edition = "2018"

[dependencies]
backtrace = "0.3"
derive-struct = { path = "../derive-struct" }
dirs = "2"
factorio-mods-common = { path = "../factorio-mods-common" }
globset = "0.4"
lazy_static = "1"
package = { path = "../package" }
semver = "0.9"
serde = "1"
serde_derive = "1"
serde_json = "1"
zip = "0.5"
