[package]
name = "factorio-mods-local"
version = "0.1.0"
authors = ["Arnavion <arnavion@gmail.com>"]

[dependencies]
appdirs = "0.2.x"
derive-error-chain = "0.11.x"
derive-struct = { version = "0.1.0", path = "../derive-struct" }
error-chain = "0.11.x"
factorio-mods-common = { version = "0.1.0", path = "../factorio-mods-common" }
globset = "0.3.x"
lazy_static = "1.0.x"
semver = "0.9.x"
serde = "1.0.x"
serde_derive = "1.0.x"
serde_json = "1.0.x"
zip = "0.3.x"
