[package]
name = "factorio-mods-local"
version = "0.1.0"
authors = ["Arnavion <arnavion@gmail.com>"]
edition = "2018"

[dependencies]
appdirs = "0.2.x"
derive-struct = { version = "0.1.0", path = "../derive-struct" }
factorio-mods-common = { version = "0.1.0", path = "../factorio-mods-common" }
failure = "0.1.x"
failure_derive = "0.1.x"
globset = "0.4.x"
lazy_static = "1.2.x"
semver = "0.9.x"
serde = "1.0.x"
serde_derive = "1.0.x"
serde_json = "1.0.x"
zip = "0.4.x"
