[package]
name = "factorio-mods-local"
version = "0.1.0"
authors = ["Arnavion <arnavion@gmail.com>"]

[dependencies]
appdirs = "0.2.x"
error-chain = "0.5.x"
factorio-mods-common = { version = "0.1.0", path = "../factorio-mods-common" }
glob = "0.2.x"
lazy_static = "0.2.x"
derive-struct = { version = "0.1.0", path = "../derive-struct" }
semver = "0.5.x"
serde = "0.8.x"
serde_derive = "0.8.x"
serde_json = "0.8.x"
zip = "0.2.x"
