[package]
name = "factorio-mods-api"
version = "0.1.0"
authors = ["Arnavion <arnavion@gmail.com>"]

[dependencies]
hyper = "0.9.x"
serde = "0.8.x"
serde_json = "0.8.x"
url = "1.2.x"

[replace]
"openssl:0.7.14" = { git = "https://github.com/Arnavion/rust-openssl", branch = "cfg-comp" }
