[package]
name = "derive-struct"
version = "0.1.0"
authors = ["Arnavion <arnavion@gmail.com>"]
edition = "2018"

[dependencies]
proc-macro2 = "0.4.x"
quote = "0.6.x"
syn = { version = "0.14.x" }

[lib]
proc-macro = true
