[package]
name = "derive-struct"
version = "0.1.0"
authors = ["Arnavion <arnavion@gmail.com>"]

[dependencies]
proc-macro2 = "0.3.x"
quote = "0.5.x"
syn = { version = "0.13.x" }

[lib]
proc-macro = true
