[package]
name = "factorio-mods-web"
version = "0.1.0"
authors = ["Arnavion <arnavion@gmail.com>"]

[dependencies]
derive-error-chain = "0.11.x"
derive-new = "0.5.x"
derive-struct = { version = "0.1.0", path = "../derive-struct" }
error-chain = "0.11.x"
factorio-mods-common = { version = "0.1.0", path = "../factorio-mods-common" }
futures = "^0.1.15"
itertools = "0.7.x"
lazy_static = "0.2.x"
reqwest = { version = "=0.8.0", features = ["unstable"] }
serde = "1.0.x"
serde_derive = "1.0.x"
serde_urlencoded = "0.5.x"
tokio-core = "0.1.x"
