[package]
name = "factorio-mods-web"
version = "0.1.0"
authors = ["Arnavion <arnavion@gmail.com>"]
edition = "2018"

[dependencies]
async-stream = "0.2"
bytes = "0.5"
derive-struct = { path = "../derive-struct" }
factorio-mods-common = { path = "../factorio-mods-common" }
failure = "0.1"
failure_derive = "0.1"
futures-core = "0.3"
futures-util = "0.3"
itertools = "0.8"
lazy_static = "1"
reqwest = { git = "https://github.com/seanmonstar/reqwest", rev = "5d639ecbde270bb44c4703c168cfce4729d9e2b3", features = ["json"] }
serde = "1"
serde_derive = "1"
serde_urlencoded = "0.6"
url = { version = "2", features = ["serde"] }

[target.'cfg(windows)'.dependencies]
native-tls = "0.2"
winapi = { version = "0.3", features = ["winerror"] }

[dev-dependencies]
tokio = { version = "0.2", features = ["macros"] }
