[package]
name = "factorio-mods-web"
version = "0.1.0"
authors = ["Arnavion <arnavion@gmail.com>"]
edition = "2018"

[dependencies]
derive-struct = { version = "0.1.0", path = "../derive-struct" }
either = "1.4.x"
factorio-mods-common = { version = "0.1.0", path = "../factorio-mods-common" }
failure = "0.1.x"
failure_derive = "0.1.x"
futures-core-preview = { version = "0.3.0-alpha.13", features = ["either"] }
futures-util-preview = { version = "0.3.0-alpha.13", features = ["compat"] }
itertools = "0.8.x"
lazy_static = "1.3.x"
reqwest = "0.9.x"
serde = "1.0.x"
serde_derive = "1.0.x"
serde_urlencoded = "0.5.x"

[dev-dependencies]
futures-util-preview = { version = "0.3.0-alpha.13", features = ["compat"] }
tokio = "0.1.x"
