[package]
name = "factorio-mods-web"
version = "0.1.0"
authors = ["Arnavion <arnavion@gmail.com>"]

[dependencies]
derive-new = { git = "https://github.com/nrc/derive-new", rev = "24e584908a783986a5fe079aca55c00526318142" }
error-chain = "0.5.x"
hyper = "0.9.x"
factorio-mods-common = { version = "0.1.0", path = "../factorio-mods-common" }
itertools = "0.5.x"
lazy_static = "0.2.x"
serde = "0.8.x"
serde_derive = "0.8.x"
serde_json = "0.8.x"
url = "1.2.x"
