[package]
name = "factorio-mods-web"
version = "0.1.0"
authors = ["Arnavion <arnavion@gmail.com>"]
edition = "2018"

[dependencies]
bytes = "0.4"
derive-struct = { path = "../derive-struct" }
factorio-mods-common = { path = "../factorio-mods-common" }
failure = "0.1"
failure_derive = "0.1"
futures-core-preview = { version = "=0.3.0-alpha.19" }
futures-util-preview = { version = "=0.3.0-alpha.19" }
itertools = "0.8"
lazy_static = "1"
reqwest = { version = "0.10.0-alpha.1", features = ["json"] }
serde = "1"
serde_derive = "1"
serde_urlencoded = "0.6"
url = "2"

[target.'cfg(windows)'.dependencies]
native-tls = "0.2"
winapi = { version = "0.3", features = ["winerror"] }

[dev-dependencies]
tokio = "0.2.0-alpha.6"
