[package]
name = "package"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Arnavion <me@arnavion.dev>"]
description = "Package solver used by fac-rs"
edition = "2018"

[dependencies]
backtrace = "0.3"
itertools = "0.10"
petgraph = "0.6"
