[package]
name = "package"
version = "0.1.0"
authors = ["Arnavion <arnavion@gmail.com>"]

[dependencies]
derive-error-chain = "0.11.x"
error-chain = "0.11.x"
itertools = "0.7.x"
multimap = "0.4.x"
petgraph = "0.4.x"
semver = "0.9.x"
