[package]
name = "package"
version = "0.1.0"
authors = ["Arnavion <arnavion@gmail.com>"]
edition = "2018"

[dependencies]
failure = "0.1.x"
failure_derive = "0.1.x"
itertools = "0.8.x"
multimap = "0.5.x"
petgraph = "0.4.x"
semver = "0.9.x"
