[package]
name = "package"
version = "0.1.0"
authors = ["Arnavion <arnavion@gmail.com>"]
edition = "2018"

[dependencies]
failure = "0.1"
failure_derive = "0.1"
itertools = "0.9"
petgraph = "0.5"
semver = "0.9"
