[package]
name = "fac"
version = "0.1.0"
authors = ["Arnavion <arnavion@gmail.com>"]

[dependencies]
factorio-mods-api = { version = "0.1.0", path = "../factorio-mods-api" }

[replace]
"openssl:0.7.14" = { git = "https://github.com/Arnavion/rust-openssl", branch = "cfg-comp" }
